source "$INSTALL_PATH/install/pacman.sh"
source "$INSTALL_PATH/install/base.sh"
source "$INSTALL_PATH/install/extras.sh"
source "$INSTALL_PATH/install/fonts.sh"
source "$INSTALL_PATH/install/dot_files.sh"
source "$INSTALL_PATH/install/theme.sh"
source "$INSTALL_PATH/install/enable_services.sh"
source "$INSTALL_PATH/install/configure_firewall.sh"
